### ISSUE TITLE
Problem z komunikatem (brak informacji o poprawności) - część 3, podstawowe operacje

### ISSUE THREAD

**Issue by kdn222** [media3-0/apki.org#1]
Po poprawnym napisaniu operacji nie wyświetla się komunikat z informacją o poprawności i button dalej, tylko nadal jest sprawdź. Dzieje się tak gdy napiszemy show=True, w przeciwnym razie jest oki.
W Bardziej skomplikowane.... i dodatkowe operatory... po błędnym wpisaniu kodu brak komunikatu, ale może to jest celowe działanie?

**Comment by Nekromancer** [comment]
Cały czas pracujemy nad tym żeby komunikaty były jak najbardziej czytelne w każdej sytuacji. O które zadanie konkretnie chodzi z tym show=True?

**Comment by kdn222** [comment]
Dzięki za odpowiedź.
W informacji podałam które to zadanie. Nie chcę spamować... Ale chciałam
tylko pomóc... Fanny ten kurs... Super robótka... Powodzenia!

Pozdrawiam,
Katarzyna Dymek-Nowak
18 wrz 2015 01:19 "Jakub Syty" <notifications@github.com> napisał(a):

**Comment by Nekromancer** [comment]
Witam ponownie

Sprawdziłem o zadanie o które Pani chodziło i tam w treści zadania jest napisane wprost że aby zaliczyć zadanie należy linijkę show=True usunąć. Jest ona tam tylko po to żeby kursant mógł zobaczyć wynik swoich obliczeń zamiast uciekać do następnego przykładu.

Myślę że faktycznie może to być nieco mylące i na pewno się temu przyjrzymy

**Comment by kdn222** [comment]
Ok, dziękuję za wyjaśnienie, już wszystko jasne. Testowaliśmy dziś z
kilkoma osobami ten kurs. Rzeczywiście czasem problem tkwi w czytaniu. Ale
fajna praca...

Pozdrawiam!
Katarzyna Dymek-Nowak

W dniu 18 września 2015 18:10 użytkownik Jakub Syty <
notifications@github.com> napisał:
