### ISSUE TITLE
Literówki

### ISSUE THREAD

**Issue by szymon3301** [media3-0/apki.org#10]
"Wkróce" zamiast "Wkrótce" na stronie głównej i "Floot" zamiast "Floor" w C# rozdział 5 lekcja 1
![image](https://cloud.githubusercontent.com/assets/14201894/10974703/a5bafbf0-83e3-11e5-8af3-eb761fe965df.png)
![image](https://cloud.githubusercontent.com/assets/14201894/10974713/aa8ec2a6-83e3-11e5-8415-d49a1070bd7d.png)

**Comment by Nekromancer** [comment]
Literówka w kursie C# już poprawiona. Na głównej zostanie poprawiona w najbliższej aktualizacji
