### ISSUE TITLE
Kurs JavaScript

### ISSUE THREAD

**Issue by RodzynBWA** [media3-0/apki.org#11]
Witaj ;)
Dziś robiąc kurs JS utknąłem na pętli for, gdzie mam wszystko dobrze ale niestety kodowanie znaków jest źle ustawione i nie mogę przejść dalej, podsyłam screena jak to wygląda. Niestety na żadnym systemie i przeglądarce nie da się tego zrobić ;)

http://imgup.pl/di/Y53R/zrzut-ekranu-z-2015-11-24-21-58-51.png

**Comment by Ami777** [comment]
Witam,

faktycznie jest problem z kodowaniem. Ale to nie zmienia faktu że w zadaniu nie jest wszystko dobrze i PL znaczki nie mają tutaj nic wspólnego.
PS. i < 9 sprawdzi elementy 0..8, nie 0..9 :)

Pozdr.

**Comment by RodzynBWA** [comment]
Aaaa :D Faktycznie :3 haha Już działa ;)
To nie zmiania fakty że trzeba będzie poprawić kodowanie znaków :)

Pozdrawiam
