### ISSUE TITLE
Nie można przejść dalej

### ISSUE THREAD

**Issue by sethendral** [media3-0/apki.org#14]
![image](https://cloud.githubusercontent.com/assets/16463523/12032349/a23dbed2-ae17-11e5-8407-97df4280f76e.png)
W pierwszej części kursu C#, po wykonaniu zadania Formatowania ciągu znaków nie można przejść dalej. Wciąż wyświetla się "sprawdź" zamiast "Dalej".

Pozdrawiam

**Comment by Nekromancer** [comment]
Wystarczy nie wyświetlać napisu na ekranie. Polecenie mówi tylko o zapisaniu ciągu znaków do zmiennej
