### ISSUE TITLE
Problem z przejsciem do kolejnego rozdzialu

### ISSUE THREAD

**Issue by johnnydrama82** [media3-0/apki.org#15]
Witam,
rozdzial 1, temat "formatowanie ciagu znakow"
Po rozwiazaniu zadania:
string string1 = "World!";
string string2 = String.Format("Hello {0}", string1);
System.Console.WriteLine(string2);
System je sprawdza i kwalifikuje jako poprawnem ale nie ma mozliwosci przejscia dalej, przez co zadanie widac jako nie zaliczone, co uniemozliwia przejscie do kolejnego rozdzialu.
Pozdrawiam

**Comment by Nekromancer** [comment]
Witam, wystarczy nie wyświetlać ciągu znaków na ekranie

**Comment by johnnydrama82** [comment]
Witaj kolega, Nie bardzo chwytam co masz na mysli. 
wpisuje kod. klikam "sprawdz", wykonanie kodu przebiega poprawnie, ale zamiast "dalej" nadal widnieje "sprawdz"

**Comment by Nekromancer** [comment]
Kwestia ta wielokrotnie jest poruszana na forum http://forum.apki.org/t/problem-formatowanie-ciagu-znakow/174

**Comment by johnnydrama82** [comment]
Ok, teraz widze w czym rzecz. Dzieki za pomoc i cierpliwosc.
Pozdrawiam

**Comment by Nekromancer** [comment]
Pozdrawiam ;)
