### ISSUE TITLE
JS / 9 zd. "Zwracanie wartości przez funkcję"

### ISSUE THREAD

**Issue by tomasztopolewski** [media3-0/apki.org#17]
System nie może zaliczyć zadania z kursu java scriptu "Zwracanie wartości przez funkcję". Cały czas wyskakuje, już drugi dzień, nawet po skasowaniu cookies taki komunikat:
Błąd! Przepraszamy, serwer w tej chwili nie odpowiada, spróbuj ponownie lub skontaktuj się z nami.

Kod do zadania:
```
function isRoomFree(room_number){
    if(free_rooms.indexOf(room_number)) {
        return true; } 
}

function showIsRoomFree(room_number){
  if (isRoomFree(room_number)){
    console.log("Pokój "+room_number+" wolny.");
  } else {
    console.log("Pokój "+room_number+" zajęty.");
  }
}

showIsRoomFree(2);
showIsRoomFree(3);
showIsRoomFree(4);
showIsRoomFree(5);
```

**Comment by Nekromancer** [comment]
Już wszystko powinno być ok
