### ISSUE TITLE
Od wczoraj brak możliwości sprawdzenia (problem z serwerem?)

### ISSUE THREAD

**Issue by Rafus** [media3-0/apki.org#18]
Czy może zostałem zablokowany, bo patrząc po innych 'błędach', które się pojawiają, to serwer działa normalnie... Może coś u mnie''?

**Comment by swidzinski** [comment]
Chyba nie, bo u mnie też nie działa ;(

**Comment by Nekromancer** [comment]
Szukamy rozwiązania

**Comment by swidzinski** [comment]
Ok, rozumiem,  dziękuję za informacje.  Powodzenia!
4 sty 2016 11:49 "Jakub Syty" <notifications@github.com> napisał(a):

**Comment by Nekromancer** [comment]
Już wszystko powinno działać
