### ISSUE TITLE
Can't choose school in "edit profile" menu.

### ISSUE THREAD

**Issue by nst1aKacperFyda** [media3-0/apki.org#2]
I can't choose my school in settings.

**Comment by Nekromancer** [comment]
Any details? Error message? Which school are you trying to apply? Język polski może? ;>

**Comment by nst1aKacperFyda** [comment]
Pewnie. Załączam zdjęcia poniżej. Z listy szkół pokazuje mi się tylko jedną, regionu też nie mogę wybrać. 

Date: Fri, 18 Sep 2015 15:16:19 -0700

**Comment by Nekromancer** [comment]
Zdjęcia trzeba wrzucać bezpośrednio na github issues. 

Natomiast co do sprawy to na chwilę obecną jest zarejestrowana tylko jedna szkoła. Jedyne co mogę poradzić to pogonic swojego edukatora do stworzenia profilu szkoły.

**Comment by nst1aKacperFyda** [comment]
Tyle, że nasz opiekun mówił, że już stworzył profil szkoły, w takim razie ponownie z nim porozmawiam.

**Comment by nst1aKacperFyda** [comment]
Okej, rozmawiałem z opiekunem, stworzył profil szkoły już na szkoleniu, większość uczestników ze szkoły zapisała się już na profil, mówił też, że na kilku komputerach nawet w szkole nie można dołączyć do profilu szkoły, próbowałem u siebie - nic, na telefonie - wciąż nic. Nie mam pojęcia czym to jest już spowodowane.

Date: Sat, 19 Sep 2015 08:34:20 -0700

**Comment by Nekromancer** [comment]
Na stronce apki.org edukator musi ponownie założyć profil szkoły. Stronka pod adresem dev.apki.org jest w pełni testowa i dane stamtąd nie są przenoszone na apki.org. Zatem wszystkie profile, kursy i projekty powinny być na portalu pod adresem apki.org.

**Comment by Nekromancer** [comment]
Już wyjaśniliśmy sprawę profili szkół i zaczynają wreszcie powstawać. 

Przypomnę tutaj jeszcze że po zgłoszeniu się do szkoły edukator musi jeszcze zatwierdzić swojego ucznia na profilu szkoły.

**Comment by DeoreXT** [comment]
Witam.
Na koncie edukatora mam brak możliwości edycji profilu szkoły. Link do fragmentu zrzutu ekranu poniżej.
![1](https://cloud.githubusercontent.com/assets/14818787/10070721/a7e4adea-62b4-11e5-8e1d-60c9d95bd65f.png)
Czy rozwiązaniem problemu jest może przełączenie konta na GitHubie na konto organizacji?
Kolejna sprawa to forum. Autoryzacja na moim koncie nie przebiega prawidłowo. Nie wiem co jest przyczyną. Na GitHubie forum.apki.org widnieje jako aplikacja zautoryzowana. Podejmowałem kilka prób usunięcia autoryzacji i ponowienia procesu od początku ale zawsze się to kończy w sposób pokazany poniżej.
![2](https://cloud.githubusercontent.com/assets/14818787/10070896/d47b6b22-62b5-11e5-9669-0e08cf83f7b0.png)
Po każdej jednak próbie aplikacja pojawia się na koncie w GitHubie jako zautoryzowana.

**Comment by Nekromancer** [comment]
@DeoreXT Wiemy co powodowało to problemy, jednak przed ich rozwiązaniem prosimy przenieść ten wątek na nowy issue (ten jest poświęcony innemu problemowi) pod adresem https://github.com/media3-0/apki.org/issues/new
