### ISSUE TITLE
serwer nie odpowiada

### ISSUE THREAD

**Issue by rusekma** [media3-0/apki.org#20]
Witam,
mimo kilku prób, powtarza się ten sam błąd - załączam zrzut ekranu. 
Będę wdzięczna za informację, czy to sytuacja chwilowa, czy ten kurs przestał być aktywny?

Dziękuję i pozdrawiam,
rusekma
![blad](https://cloud.githubusercontent.com/assets/16461704/12091387/0e784002-b2f7-11e5-9751-a057a54dbe9e.png)

**Comment by Nekromancer** [comment]
Cały czas pracujemy nad rozwiązaniem tego problemu, duplikat https://github.com/media3-0/apki.org/issues/18

**Comment by rusekma** [comment]
Dziękuję i powodzenia!

**Comment by Nekromancer** [comment]
Już powinno być wszystko ok
