### ISSUE TITLE
Java podstawy etap 3

### ISSUE THREAD

**Issue by piernikos** [media3-0/apki.org#21]
nie zalicza zadań:
Typ boolean
Typ number
Typ string
po sprawdzeniu kodu wyświetla pod wynikiem "Super!", po rozwiązaniu quizu nie przechodzi do etapu 4

**Comment by Ami777** [comment]
Bardzo proszę:
1. Nazwa kursu dokładna (JavaScript podstawy rozumiem?)
2. Wysłać to na forum.apki.org
3. Koniecznie załączyć screena.
