### ISSUE TITLE
Błąd w kursie C#

### ISSUE THREAD

**Issue by Sylwia0895** [media3-0/apki.org#22]
W 4 przykładzie pomimo wyświetlenia że kod został dobrze napisany nie można kliknąć "Dalej".

**Comment by Nekromancer** [comment]
Aby zaliczyć zadanie nie wolno wyświetlać nic na ekranie (należy usunąć wszystkie linie `System.out.print`

**Comment by Sylwia0895** [comment]
Dziękuję za podpowiedź , zadziałało :)
