### ISSUE TITLE
Błąd przy sprawdzianiu.

### ISSUE THREAD

**Issue by afrischkemuth** [media3-0/apki.org#25]
Po zrobieniu zadania przychodzi komunikat  "Błąd! Przepraszamy, serwer w tej chwili nie odpowiada, spróbuj ponownie lub skontaktuj się z nami.". Proszę o jak najszybsze rozwiązanie problemu, ponieważ utrudnia to bardzo prace

**Comment by Nekromancer** [comment]
Duplikat https://github.com/media3-0/apki.org/issues/26
