### ISSUE TITLE
Błąd! Przepraszamy, serwer w tej chwili nie odpowiada.

### ISSUE THREAD

**Issue by mkropidlowski** [media3-0/apki.org#28]
Witam, po korzystaniu z kursu JS, po wpisaniu kodu i kliknięciu Sprawdź, wyskakuje komunikat: "Błąd! Przepraszamy, serwer w tej chwili nie odpowiada, spróbuj ponownie lub skontaktuj się z nami." Czy można coś z tym zrobić?

**Comment by Dzieciuchd** [comment]
Poczekaj kilka godzin, pomoże :)

**Comment by afrischkemuth** [comment]
Dodam,  że to nie pierwszy raz. Rozumiem, że to jest BETA ale bez przesady

**Comment by afrischkemuth** [comment]
Kolega 2 ławki dalej też tak miał. Od tego zależy nasza ocena...

**Comment by Gliwinski** [comment]
Sewer w tej chwili nie odpowiada. To juz kolejny raz. Prosze cos z tym zrobić.

**Comment by Dzieciuchd** [comment]
Już wczoraj pisałem ale widocznie nie są w stanie nic zrobić, chyba trzeba będzie usunąć konta. Jest nas 13 w klasie, bardzo wymagających ludzi i nie możemy sobie pozwolić na takie rzeczy. Prosimy, naprawcie to, chcemy zdać :)

**Comment by afrischkemuth** [comment]
Pan Gliwiński to już wgl. Miał 1/2 na półrocze. Ledwo zaliczył ten przedmiot, a teraz myślał że wpadnie jakaś łatwa ocena, a tu takiego wała. Myślałem że chłopak się załamie.

**Comment by PatrykChornicki** [comment]
natasz natasz 
szatan szatan

**Comment by PatrykChornicki** [comment]
ups, przepraszam mam zespół torenta

**Comment by Gliwinski** [comment]
Pan Frischkemuth też miał 1 na koniec roku szkolnego i musiał poprawaić cały rok. Myślał że dostanie dobrą ocenę a dostał najniższą z całej klasy. Reszta klasy chce zdać do następnej klasy.

**Comment by afrischkemuth** [comment]
Jak administrator zobaczy składnie wypowiedzi Pana Gliwinskiego, to się przez chwile zastanowi kto miał 1 na koniec.

**Comment by Dzieciuchd** [comment]
TO WASZ KOD JEST ZLY

**Comment by Gliwinski** [comment]
Niech każdy zajmie się sobą a nie czyimiś ocenam Panie Frischkemuth

**Comment by afrischkemuth** [comment]
Proszę o zacytowanie wypowiedzi Pana Dzieciuchd ponieważ gdzieś już to słyszałem

**Comment by TI2R14D11** [comment]
Myślę że to odpowiednia chwila aby dodać iż Gliwiński robi prawo jazdy kategorii A, ciężko pracuje mu się w stresie kiedy widzi, że program nie działa. Wczoraj kładł styropian ze szwagrem a 23 Lutego PKK pobrało jego dokumenty przez WORD co powoduje że Kamil jest w nadmiernym stresie

**Comment by Dzieciuchd** [comment]
Dodam iz montowal wczoraj odkurzacze, oraz odkurzal nimi swoj telefon i komputor

**Comment by Komar159** [comment]
KAT A 18 LAT

**Comment by Gliwinski** [comment]
Niech Pan Kuleta zajmie się sobą i swoim BMW bo kiedys może stać się cos czego nawet nie będzie wiedział

**Comment by afrischkemuth** [comment]
Пожалуйста, как можно скорее отремонтировать страницу

**Comment by Bolebor1** [comment]
camillo, wąchaj pałe

**Comment by TI2R14D11** [comment]
Niech tylko zobaczę nową ryskę ma moim ślicznym aucie Kamilo, będę wiedział do kogo się zgłosić i kto mi wyłoży na lakierke, a jak już w temacie jesteśmy to co robisz jutro bo chciałem do Moskwy po paliwo z Tobą skoczyć

**Comment by Komar159** [comment]
sprzedam opla

**Comment by Bolebor1** [comment]
sprzedam narkotyki

**Comment by PatrykChornicki** [comment]
卡米爾是一個踏板

**Comment by Bolebor1** [comment]
żartowałem admin z tymi narkotykami jak coś

**Comment by Dzieciuchd** [comment]
Kupie jelonka

**Comment by Dzieciuchd** [comment]
do expa

**Comment by mkropidlowski** [comment]
mam, PRIV ch1 śr. 40

**Comment by Dzieciuchd** [comment]
str wsi

**Comment by Dzieciuchd** [comment]
kapitan

**Comment by Dzieciuchd** [comment]
gura sochan

**Comment by mkropidlowski** [comment]
A polurujesz? 100k płace.

**Comment by Dzieciuchd** [comment]
lur plis

**Comment by Dzieciuchd** [comment]
ale w pt

**Comment by HnatiukPiotr** [comment]
pobufuje

**Comment by PatrykChornicki** [comment]
Też bym coś zaj*bał w nos

**Comment by Dzieciuchd** [comment]
buf leczenie ?

**Comment by Bolebor1** [comment]
http://www.redtube.com/

**Comment by TI2R14D11** [comment]
Kamil, chciałem cie poinformować że po szkole jadę na komisariat policji w Nowym Dworze Gdańskim i będę zmuszony zgłosić twoją groźbe. ~Art. 190 Kodeksu Karnego Groźba Karalna. "Zastraszanie i wszystkiego typu prześladowania są karalne grzywną w wysokości 8000 PLN i 4 lat pozbawienia wolności"  8000 PLN, Kamilo, sam wiesz jakie to są liczby, oko już by za to zrobił

**Comment by mkropidlowski** [comment]
Też z programowaniem strona?

**Comment by Bolebor1** [comment]
si kalafą

**Comment by Komar159** [comment]
# _**HAHAA**_

**Comment by Gliwinski** [comment]
Panie Macieju prosze lepiej się postarać bo tym mmoże Pan do gimnazjum pójść i tak mówić.

**Comment by Bolebor1** [comment]
aha

**Comment by TI2R14D11** [comment]
dawaj na przerwe

**Comment by TI2R14D11** [comment]
"Panie Macieju prosze lepiej się postarać bo tym mmoże Pan do gimnazjum pójść i tak mówić" - Gliwinski, wyjaśnisz?

**Comment by Bolebor1** [comment]
jeszcze, gdy chodziłem to był tam taki Paweł i ja jechałem na roweże i go spotkałem...
i poźniej jeszcze pojechaliśmy do Biedronki na lody, a później to już do domu pojechaliśmy

**Comment by HnatiukPiotr** [comment]
elo

**Comment by Gliwinski** [comment]
Pomyśl, to zrozumiesz

**Comment by Bolebor1** [comment]
sam se pomyśl

**Comment by Bolebor1** [comment]
Po prawej stronie znajduje się kod ze zmiennymi zawierającymi ilość łóżek w każdym z pokoi hotelowych. Klient właśnie dzwoni zapytać o cenę pokoju 1. Cena każdego pokoju wynosi 50 zł za każde łóżko plus 20 zł kosztów obsługi. Policz i wyświetl na ekranie opłatę należącą się tylko za pokój 1.

**Comment by Bolebor1** [comment]
"Dostanie nowego imienia w sakramencie bierzmowania od biskupa Jana Styrny - Karol."

**Comment by Gliwinski** [comment]
Zajmij się sobą

**Comment by Komar159** [comment]
_**WLASNIE **_

**Comment by Bolebor1** [comment]
dobra sory kamilo

**Comment by TI2R14D11** [comment]
Kamil to co porysujesz mi autko ;(?

**Comment by PatrykChornicki** [comment]
JESZCZE RAZ SIĘ ODEZWIESZ PARÓWO , TO POGADAMY INACZEJ !

**Comment by Gliwinski** [comment]
Twoje auto Maciej to zabytek

**Comment by Bolebor1** [comment]
ahaahah

**Comment by Bolebor1** [comment]
ostro teraz napisał

**Comment by TI2R14D11** [comment]
w tym momencie obraźiłeś Patryka, Komara, Piotrka i wszystkich posiadaczy aut z poniżej 1999

**Comment by PatrykChornicki** [comment]
ZARAZ TY MOŻESZ BYĆ ZABYTKIEM JAK CIĘ POSKŁADAM W 10 CZĘŚCI

**Comment by PatrykChornicki** [comment]
POGADAMY NA WF

**Comment by Gliwinski** [comment]
Co myslicie że siię przestraszę

**Comment by Komar159** [comment]
# _**O MATKO **_

**Comment by PatrykChornicki** [comment]
HAAHHAHHAHA

**Comment by Bolebor1** [comment]
KSW 34: Gliwiński vs Kuleta

**Comment by TI2R14D11** [comment]
Wstępnie 14:25 godzina walki

**Comment by TI2R14D11** [comment]
Kamilo, a ty gdzie masz swojego Opelka Vectra B z 2006r w brązowych skórach 4sec. do setki?

**Comment by Gliwinski** [comment]
Twój samochód do niego to nastarszy zabytek jaki kolwiek jest w Polsce

**Comment by TI2R14D11** [comment]
twoja konstrukcja zdań jest kurwa porażająca XD

**Comment by Gliwinski** [comment]
Twoja też

**Comment by PatrykChornicki** [comment]
Zamknij się żulu

**Comment by TI2R14D11** [comment]
a od Beatki to ty się odczep brudasie bo nie ręczę za siebie, ostatnio przepuściłem cię na pasach, teraz możesz mieć problem

**Comment by Bolebor1** [comment]
Kamilo ma taką zajebistą vectre, ma prawko, i dlatego woli jeździć pksem albo starsi po niego przyjeżdżają czerwoną astrą

**Comment by PatrykChornicki** [comment]
Maciej, dołączam się do przedsięwzięcia

**Comment by TI2R14D11** [comment]
@Gliwinski ustaw sobie na dzwonek "Mamy przejebane"

**Comment by Bolebor1** [comment]
#KAROLMUSISZ

**Comment by Gliwinski** [comment]
A ty Bolebor lepiej się odczep bo sam nie masz wózka a gadasz za innych

**Comment by Bolebor1** [comment]
no ja nie mam

**Comment by Bolebor1** [comment]
al przynajmniej się nie filmuje że mam

**Comment by Kolesiek** [comment]
@Gliwinski W twoim plecaku jest bomba, spierdalaj lepiej... 3....2.....1....

**Comment by Bolebor1** [comment]
ale

**Comment by Gliwinski** [comment]
Możesz jedynie rowerem jeździć Bolebor

**Comment by PatrykChornicki** [comment]
JESZCZE RAZ COŚ POWIEDZ NA KOGOŚ

**Comment by Bolebor1** [comment]
tak jak ty synu

**Comment by Gliwinski** [comment]
Bo nie umiesz prowadzić auta

**Comment by PatrykChornicki** [comment]
KURWA ZAMKNIJ PIZDE, JESZCZE RAZ COŚ NAPISZESZ 

!!

**Comment by Bolebor1** [comment]
mieć prawko i nie umieć jeździć

**Comment by TI2R14D11** [comment]
Kamilo, on chociaż ma prawo jazdy XD

**Comment by Gliwinski** [comment]
Bo co Wolność słowa mamy i każdy może pisać co chce

**Comment by Kolesiek** [comment]
Witam panow. Z okazji zaistnialej sytuacji musze przedzwonic do waszego nauczyciela od informatyki i bede zmuszony niestety zbanowac wszystkich ktorzy tu pisali. A @Gliwinski idzie na policje !

**Comment by PatrykChornicki** [comment]
JAPA TAM !

**Comment by TI2R14D11** [comment]
ale możesz wyłapać

**Comment by TI2R14D11** [comment]
Patryk z początku robił sobie żarty, teraz to już widzę że nawet się nie uśmiecha. Kamilo masz przejebane

**Comment by Kolesiek** [comment]
**Groźby są karalne.**

**Comment by Gliwinski** [comment]
Właśnie

**Comment by PatrykChornicki** [comment]
SORY SZEFIE , PROSZE ZGŁOSIĆ KAMILA G.

**Comment by mkropidlowski** [comment]
Tak

**Comment by Kolesiek** [comment]
Wiec panie @Gliwinski prosze nikogo nie obrazac a najlepiej jezeli pan chce uniknac kary to usunac komentarze i powiedziec od nowa o co chodzi z ta strona "Apki.org"

**Comment by Gliwinski** [comment]
A ty się nie wtrącaj Kolesiek

**Comment by Kolesiek** [comment]
**Bedac administratorem poniekad mam obowiazek sie wtracic**

**Comment by PatrykChornicki** [comment]
BO CO ?

**Comment by Kolesiek** [comment]
**Radze sie zastosowac do polecen bo dosiegnie pana kara.**

**Comment by Komar159** [comment]
# _**AHAH**_

**Comment by TI2R14D11** [comment]
Cześć chłopaki

**Comment by Nieobliczalny07** [comment]
SIARA

**Comment by TI2R14D11** [comment]
PRZESTANIECIE?

**Comment by Nieobliczalny07** [comment]
A MOŻE JA SOBIE SZEDŁEM ? CO ?

**Comment by Dzieciuchd** [comment]
Please be quiet :8ball:

**Comment by KamilKarol** [comment]
a może ja sobie szedłem żeby sobie gdzieś iść?

**Comment by Nekromancer** [comment]
Gratuluję poziomu mentalnego kolegów, naprawdę pozazdrościć.

Co do błędu - zgłoszenie to duplikat https://github.com/media3-0/apki.org/issues/26
