### ISSUE TITLE
Sprawdzanie kodu nie działa

### ISSUE THREAD

**Issue by TheMikirog** [media3-0/apki.org#31]
Witam!
Wszedłem świeżo na stronę i chciałem wypróbować jeden z kursów. Postanowiłem wziąć na pierwszy ogień Pythona. Podstawy nie zaszkodzi spróbować. Po uruchomieniu pierwszego zadania napisałem kod i chciałem go sprawdzić. Niestety okno sprawdzania odmawiało mi posłuszeństwa. Kod był w 100% poprawny a mimo to nie było żadnego komunikatu czy źle, czy dobrze i tak dalej. Wpisałem nawet losowe litery i ciągle bez odpowiedzi. Nie znam języka programowania, który potraktowałby losowe litery jako kod, który może rozczytać. Uznałem więc, że może brakuje mi jakiegoś dodatku, jak Flash Player czy coś, ale przycisk reagował i była animacja trybika. 

[Tutaj krótki filmik jak to mniej więcej wyglądało](https://www.youtube.com/watch?v=30W-6wnKO5c&feature=youtu.be)

**Comment by Kurnikowa** [comment]
Witam. 

Strona naprawdę wygląda ok, natomiast przy sprawdzaniu kodu - ten sam problem, po prostu nic się nie dzieje, a jest tylko animacja ikonki. Czasami pomagało odświeżenie strony, napisanie kodu ponownie, ale to rzadko działa.

**Comment by Nekromancer** [comment]
Witam
Kompilacja kodu i uruchamianie go jest oparte o usługę zewnętrzną (portal Hackerearth). Stabilność tego serwisu jednak pozostawia dużo do rzeczenia. W sytuacjach gdy ich serwery nie odpowiadają apki.org nie są w stanie funkcjonować poprawnie. Jedynym przyszłościowym rozwiązaniem takiego problemu byłoby napisanie własnej usługi kompilacji kodu lub zmiany dostawcy na bardziej stabilnego.

**Comment by Nekromancer** [comment]
https://github.com/media3-0/apki.org/issues/26

**Comment by kinioreklolek12345** [comment]
mam ten sam problem
