### ISSUE TITLE
Kurs języka Python - część 5 - Dodatkowe operacje na ciągach znaków

### ISSUE THREAD

**Issue by TomLewN** [media3-0/apki.org#4]
Treść zadania niedopracowana
![2015-09-22 20_10_35-apki org](https://cloud.githubusercontent.com/assets/14029131/10027199/0e75eb6e-6166-11e5-9d51-ded399a9d452.jpg)

**Comment by Nekromancer** [comment]
Co w tej treści jest niedopracowane? Nie mieliśmy innych zgłoszeń że to zadanie jest niejasne
