### ISSUE TITLE
Niepoprawna autoryzacja forum.apki.org

### ISSUE THREAD

**Issue by DeoreXT** [media3-0/apki.org#5]
Autoryzacja forum.apki.org na moim koncie nie przebiega prawidłowo. Nie wiem co jest przyczyną. Na GitHubie forum.apki.org widnieje jako aplikacja zautoryzowana. Podejmowałem kilka prób usunięcia autoryzacji i ponowienia procesu od początku ale zawsze się to kończy w sposób pokazany poniżej.
![2](https://cloud.githubusercontent.com/assets/14818787/10070896/d47b6b22-62b5-11e5-9669-0e08cf83f7b0.png)
Po każdej jednak próbie aplikacja pojawia się na koncie w GitHubie jako zautoryzowana.

**Comment by Nekromancer** [comment]
Z tego co widzę w bazie danych to próbuje się Pan autoryzować za pomocą nowego konta github. Czy nie tworzył go Pan na nowo? 

Na Forum teraz już powinno działać (stare konto zostało usunięte).

**Comment by DeoreXT** [comment]
Zgadza się. Już działa.
