### ISSUE TITLE
Brak możliwość edycji profilu szkoły

### ISSUE THREAD

**Issue by DeoreXT** [media3-0/apki.org#6]
Na koncie edukatora nie mam możliwości edycji profilu szkoły. Link do fragmentu zrzutu ekranu poniżej.
![1](https://cloud.githubusercontent.com/assets/14818787/10070721/a7e4adea-62b4-11e5-8e1d-60c9d95bd65f.png)
Czy rozwiązaniem problemu jest może przełączenie konta na GitHubie na konto organizacji?

**Comment by Nekromancer** [comment]
Konta na portalu apki.org na Pana maila istnieją 2 - jedno (starsze) ma uprawnienia edukatora, natomiast nowe nie. Czy tworzył Pan nowe konto na portalu github?

Żeby rozwiązać tą sprawę to musi się Pan zdecydować z którego konta będzie Pan korzystał. Następnie usunę zduplikowane konto i trzeba będzie na nowo stworzyć profil szkoły (który już istnieje, ale jest przypisany do starego konta).

**Comment by DeoreXT** [comment]
Tak tworzyłem nowe konto na GitHubie. Proszę stare usunąć i przypisać uprawnienia do nowego. Uzupełnię profil szkoły ponownie.
Przepraszam za zamieszanie

**Comment by Nekromancer** [comment]
Już naprawiłem wszystko, może Pan założyć nowy profil
