### ISSUE TITLE
Budowanie treści zadań

### ISSUE THREAD

**Issue by krzychu1200** [media3-0/apki.org#7]
Witam,
Wychodzę z propozycją drobnej lecz dla uczących się istotnej kwestii, jeśli to nie problem to proszę aby podczas budowy treści zadania układać wszystkie czynności po kolei np. zamiast

"Stwórz funkcję, która ma 3 argumenty - nazywają się one arg1, arg2, arg3, z czego argument arg3 na wartość domyślną "!". Funkcja ta dodaje do siebie te argumenty i zwraca je słowem return. Funkcja zostanie automatycznie przetestowana. Powinna mieć nazwę - test"

"Stwórz funkcję o nazwie test która posiada 3 argumenty nazywające się kolejno arg1, arg2, arg3, dla arg3 ustaw wartość domyślną "!" ..."

Myślę że wiadomo o co chodzi, pisanie zadania w kolejności jego wykonywania bardzo by pomogło w rozeznaniu się na czym się skończyło.

**Comment by Nekromancer** [comment]
Hmm szczerze mówiąc jak dla mnie nie ma specjalnej różnicy między takimi sformułowaniami, ale jest to jak najbardziej do przegadania
