### ISSUE TITLE
Python - Konstruktor z argumentami

### ISSUE THREAD

**Issue by Triadrian** [media3-0/apki.org#80]
Cześć,

Rozwiązałem zadanie (w tytule) i pokazuje wynik, ale nie zalicza lekcji. Nie wiem co mam zrobić, żeby mi zaliczyło.
Poza tym bardzo często jak mam jakiś błąd to nie pokazuje żadnego erroru. W zasadzie to nic nie pokazuje i nie wiem nawet gdzie szukać błędu. Fajnie jak byście nad tym popracowali.

Dzięki,
Triadrian

**Comment by Triadrian** [comment]
Już poszło. Wpisałem "ilość kalorii to: " zamiast "Ilość kalorii to: " :| No bez przesady.

**Comment by jakoss** [comment]
Dlaczego bez przesady? Nikt nie jest w stanie przewidzieć wszystkiego co wymyślił użytkownik. Wymagamy konkretnego ciągu znaków więc i taki musi się znaleźć na wyjściu

**Comment by Triadrian** [comment]
No rozumiem, ale mała i wielka literka? Poza tym dlaczego w takim ciągu znaków nie mogę sobie wpisać co mi się podoba? To chyba nie ma znaczenia większego.

**Comment by jakoss** [comment]
Zadanie jest bardzo proste i wymaga użycia konkretnej konstrukcji. 

Kurs można przygotować na setki różnych sposobów, autor tego przyjął akurat taki. Dyskusja na temat "znaczenia" jest tutaj naprawdę bezcelowa

**Comment by Triadrian** [comment]
Jasne, chodzi mi tylko o to, że do nauki budowania klas nie ma chyba większego znaczenia co sobie wpiszę w stringu. Już nie męczę dalej.
Natomiast druga część problemu, czyli brak wiadomości o błędzie przydałby się znacznie bardziej.
Tak poza tym, dzięki, że to robicie!! A mogę gdzieś wyrazić zainteresowanie jakimś konkretnym językiem? :)

**Comment by jakoss** [comment]
Ja na chwilę obecną nie pracuję już nad apkami. Wszystkim zajmuje się Fundacja Media 3.0, zatem wszystkie takie sprawy powinny być kierowane do nich
